### ISSUE TITLE
Follow wikidata links in Wikipedia

### ISSUE THREAD

**Issue by teolemon** [derenrich/wwwyzzerdd#17]
### What 
Follow wikidata links in Wikipedia
It's possible to add manual wikidata links in Wikipedia. Adding the dot next to those would be useful

<img width="367" alt="Capture d’écran 2022-06-11 à 17 59 22" src="https://user-images.githubusercontent.com/1689815/173195411-9c40739d-19af-4267-a5d4-aac81b29b6cf.png">

**Comment by teolemon** [comment]
- Here it is (APG management link) https://en.wikipedia.org/wiki/Soci%C3%A9t%C3%A9_G%C3%A9n%C3%A9rale#Board_of_Directors
- So I have another example with a link to French Wikipedia (the page does not exist in English, but does in French): https://en.wikipedia.org/wiki/Soci%C3%A9t%C3%A9_G%C3%A9n%C3%A9rale#Board_of_Directors

**Comment by derenrich** [comment]
Thanks. This was resolved in https://github.com/derenrich/wwwyzzerdd/commit/a6f0af487126e84a5273fc1d2257937a904af229

It has been submitted to the FF and Chrome stores but who knows how long it'll take for them to update.
