### ISSUE TITLE
identifier that are case insensitive aren't treated that way

### ISSUE THREAD

**Issue by derenrich** [derenrich/wwwyzzerdd#27]

**Comment by VladimirAlexiev** [comment]
This is item 1 of [Ideas / Requests](https://www.wikidata.org/wiki/Wikidata_talk:Wwwyzzerdd#Ideas_%2F_Requests)

**Comment by derenrich** [comment]
This is fixed in 121a9e156ca77e28108e528ccb9d4d4b4fb285e4
