### ISSUE TITLE
Do not activate on Revision pages

### ISSUE THREAD

**Issue by PythonCoderAS** [derenrich/wwwyzzerdd#38]
For example, on https://en.wikipedia.org/w/index.php?title=Swashbuckle_(TV_series)&curid=44332620&action=history, I still see orbs for section headings, which I don't think should happen.

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/13932583/209437824-73cc4ebb-7cf2-458f-9452-8e85aafe9da1.png">

**Comment by derenrich** [comment]
good point i'll look into this

**Comment by derenrich** [comment]
this is fixed in 3dcc72b34f7cbcc9506a382acccc08c1d8320556 it'll be in the next release
