### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by DatGuy1** [derenrich/wwwyzzerdd#44]
A single orb is displayed after the title, suggesting an 'instance of' statement for the article.
```
frontend.js:7 Uncaught Error: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.u (frontend.js:7:122755)
    at window.onload (frontend.js:14:78143)
```

**Comment by derenrich** [comment]
oh dear. what version are you using? what browser?

**Comment by derenrich** [comment]
try using the "Clear Cache" option to see if that fixes it?

**Comment by DatGuy1** [comment]
Wwwyzzerdd v0.0.3.4, Chrome 109.0.5414.76. Clear cache didn't fix it.

**Comment by derenrich** [comment]
Ugh, I'm real sorry. Unfortunately this isn't replicating for me. I do remember running into this error at some point and I believe it's fixed in my most recent branch. I don't think this error is related to the rest of the app not working though. 

Unfortunately, I'm in the middle of a large refactor so cutting a release is a bit risky. But I'll investigate further.

**Comment by derenrich** [comment]
try going to the "manage extensions page" for wwwyzzerdd (I think it's at chrome://extensions/?id=gfidggfngdnaalpihbdjnfbkfiniookc for you) and checking the "site access" list. It should have granted access to wikipedia/wikidata/huggingface. your bug replicates if wikidata is unchecked. I'm not sure why that would happen though.

**Comment by DatGuy1** [comment]
Yep, that's it.

**Comment by derenrich** [comment]
do you have any idea why it would've gotten toggled?

**Comment by DatGuy1** [comment]
Probably because I changed the extension to work on button click rather than everytime, and so it turned off site access globally. I reenabled wikidata and huggingface and it now works.
