### ISSUE TITLE
Incorrect value extracted for P9198 from enwiki

### ISSUE THREAD

**Issue by kbseah** [derenrich/wwwyzzerdd#59]
Hello, I used Wwwyzzerdd to make this edit: https://www.wikidata.org/w/index.php?title=Q182064&diff=prev&oldid=2240707479

However it appears to have extracted the wrong value for the property P9198 (Encyclopédie berbère article ID) from the enwiki article https://en.wikipedia.org/wiki/Djellaba

A claim with the correct value, `2181`, was already present on the Wikidata item. Wwwyzzerdd extracted `218` instead. The link that was highlighted in the article was http://journals.openedition.org/encyclopedieberbere/2181

**Comment by derenrich** [comment]
I looked into this and it seems like this is primarily an issue in the regex being used in the property. I updated the property to try to fix it.

**Comment by kbseah** [comment]
Thank you!
