### ISSUE TITLE
Extension removes Wikipedia footer/links

### ISSUE THREAD

**Issue by todrobbins** [derenrich/wwwyzzerdd#9]
This part of the footer disappears when the extension is active (I'm using Firefox 94.0.1):

![image](https://user-images.githubusercontent.com/158590/142355424-3ba25cb4-7d3a-4706-9dd9-6f6f3624cb86.png)

**Comment by derenrich** [comment]
Huh, I hadn't noticed this. I'll try to take a look at it today. Thanks for
the report

**Comment by derenrich** [comment]
Ok this is resolved by https://github.com/derenrich/wwwyzzerdd/commit/b2fc264b19318224bb6dc9ccb3a4399c378875dd which will be in the next release. Thanks.
